#ifndef GUARD_CONSTANTS_BALL_SEALS_H
#define GUARD_CONSTANTS_BALL_SEALS_H

#define BALL_SEAL_NONE 0x0
#define BALL_SEAL_HEARTCLOUD_SMALL_PINK 0x1
#define BALL_SEAL_HEARTSPIN_SMALL_PINK 0x2
#define BALL_SEAL_HEARTCIRCLE_SMALL_PINK 0x3
#define BALL_SEAL_LETTER_A 0x4
#define BALL_SEAL_ORBS_RAINBOW 0x5
#define BALL_SEAL_6 0x6
#define BALL_SEAL_7 0x7
#define BALL_SEAL_8 0x8
#define BALL_SEAL_9 0x9
#define BALL_SEAL_A 0xA
#define BALL_SEAL_B 0xB
#define BALL_SEAL_C 0xC
#define BALL_SEAL_D 0xD
#define BALL_SEAL_E 0xE
#define BALL_SEAL_F 0xF
#define BALL_SEAL_10 0x10
#define BALL_SEAL_11 0x11
#define BALL_SEAL_12 0x12
#define BALL_SEAL_13 0x13
#define BALL_SEAL_14 0x14
#define BALL_SEAL_15 0x15
#define NUM_BALL_SEALS 0x16

#endif  // GUARD_CONSTANTS_BALL_SEALS_H
